"""Add turmas and reservas tables

Revision ID: da22c9a77215
Revises: 25b5a3a9cbe3
Create Date: 2026-05-26 19:43:29.739940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da22c9a77215'
down_revision: Union[str, None] = '25b5a3a9cbe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turmas',
    sa.Column('codigo_turma', sa.String(length=50), nullable=False),
    sa.Column('nome_curso', sa.String(length=100), nullable=False),
    sa.Column('instrutor', sa.String(length=100), nullable=False),
    sa.Column('carga_horaria', sa.Integer(), nullable=False),
    sa.Column('turno', sa.String(length=50), nullable=False),
    sa.Column('regime_dias', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('codigo_turma')
    )
    op.create_index(op.f('ix_turmas_codigo_turma'), 'turmas', ['codigo_turma'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.String(length=50), nullable=False),
    sa.Column('data', sa.String(length=50), nullable=False),
    sa.Column('turno', sa.String(length=50), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.codigo_turma'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_id'), 'reservas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservas_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_turmas_codigo_turma'), table_name='turmas')
    op.drop_table('turmas')
    # ### end Alembic commands ###
